### ISSUE TITLE
Billing period

### ISSUE THREAD

**Issue by RashidJa** [vippsas/vipps-recurring-woocommerce#12]
If you have a subscription that is charged every 2nd week or every 3rd month, it shows up in the vipps app as charged every week or every month. It seems IntervalCount is set to 1. Should it no be fetched from get_billing_interval?

**Comment by Marcuzz** [comment]
Good catch. It appears this was overlooked!

**Comment by Marcuzz** [comment]
This will be fixed in v1.3.0 :)

Thanks for reporting the issue!
