### ISSUE TITLE
PHP error when checking pending orders

### ISSUE THREAD

**Issue by RashidJa** [vippsas/vipps-recurring-woocommerce#15]
When force checking pending orders I get the following PHP notice: 
 
file: "wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/class-wc-gateway-vipps-recurring.php"
line: 414
message: "Trying to access array offset on value of type bool"
stack: Array(4)
0: "WC_Gateway_Vipps_Recurring->check_charge_status()"
1: "WC_Vipps_Recurring->check_order_statuses()"
2: "WC_Vipps_Recurring->wp_ajax_vipps_recurring_force_check_charge_statuses()"
3: "do_action('wp_ajax_vipps_recurring_force_check_charge_statuses')"

**Comment by Marcuzz** [comment]
Hi,

What version of PHP are you using?

**Comment by RashidJa** [comment]
7.4.

**Comment by Marcuzz** [comment]
Yeah, I see what's happening here. It's an edge case where an agreement is STOPPED or EXPIRED but does not actually have a charge, so when it's trying to determine whether or not to cancel the charge it can't.

I've fixed this in the next version which should be released shortly :)
