### ISSUE TITLE
Not compatible with Wordpress 5.4.2

### ISSUE THREAD

**Issue by knotteliten85** [vippsas/vipps-recurring-woocommerce#17]
I use this plugin with woocommerce subscriptions, but when I activate the WS plugin, Vipps disappear.  All the buttons and on the cart page.  I get a message on the checkout page that no payment gateway is connected.  
In woocommerce staus I see that Vipps is not tested with the Wordpress version I use 5.4.2

This is very frustrating, because I was recommended by Vipps to use these plugins together.  And now nothing works.

**Comment by Marcuzz** [comment]
It works with WordPress 5.4.2, I just haven't updated the "tested up to" since the previous patch version. 5.4.2 is a _minor patch version_ and does not break the functionality of Vipps Recurring.

What does your product configuration look like? Have you made sure it's actually a subscription product? There are a lot of things that can cause a payment gateway to not show up.

**Comment by knotteliten85** [comment]
Hi Markus
Thank you for your fast response.
I am a bit confused about what I need to have Vipps and recurring payments, and what works with what.
I was told by Vipps that I had to use the plugin VIPPS PÅ NETT along with VIPPS LOGIN and WOOCOMMERCE SUBSCRIPIONS.
However, when I connect the Woocommerce subscriptions Vipps falls out completely.

I was in contact with Woocommerce subscription support, and they told me that Vipps på nett was not one of the payment gateways that you could use with the plugin.  They suggested that I use the plugin VIPPS RECURRING PAYMENTS instead.

I tried that, but Vipps is still gone and when I go to the chart page the Proceed to checkout button does not work at all.

When I remove the Woocommerce subscriptions plugin, the Vipps buttons are again visible, but when I go to the cart page and press Proceed to checkout, I am told that Vipps is temporarily unavailable.

The products I test with are all set up for recurring payments.

I have added the API for testing Vipps since the account is not approved of yet.

I now have all three plugins installed and active, and the two Vipps plugins are registered in the products edit.

I hope you can figure out what is wrong, or if I have done something wrong in setting things up.


Vennlig hilsen
Anne Cecilie Nygård
Annec Design

www.annec.no<http://www.annec.no/>
tlf: 932 88 706
[cid:image004.png@01D640BD.191743C0]

Fra: Marcus <notifications@github.com>
Sendt: torsdag 11. juni 2020 19.11
Til: vippsas/vipps-recurring-woocommerce <vipps-recurring-woocommerce@noreply.github.com>
Kopi: knotteliten85 <post@annec.no>; Author <author@noreply.github.com>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Not compatible with Wordpress 5.4.2 (#17)


It works with WordPress 5.4.2, I just haven't updated the "tested up to" since the previous patch version. 5.4.2 is a minor patch version and does not break the functionality of Vipps Recurring.

What does your product configuration look like? Have you made sure it's actually a subscription product? There are a lot of things that can cause a payment gateway to not show up.

**Comment by Marcuzz** [comment]
Hei igjen,

Vi tar dette på norsk siden det sikkert er lettere 😄 

Har du en testside det er mulig å gi meg tilgang til? (e-post: marcus.dahl@everyday.no). Jeg tror det er best at jeg får tatt en ordentlig titt på problemet siden det er så mye forskjellig som kan være feil. 

Jeg testet nettopp å ha WooCommerce (versjon 4.2.0), WooCommerce Subscriptions og begge Vipps-pluginene installert samtidig på Wordpress 5.4.2 og jeg opplever ikke det samme problemet, noe som er veldig snodig!

**Comment by knotteliten85** [comment]
Hei Marcus
Her kommer login til nettsiden til Crossfit Finnsnes
Bn:  Marcus
Pass:  V@52Inl#k1Ds$Q6A9BqG)d!d

Håper du klarer å finne ut av hva som kan være galt 😊

Vennlig hilsen
Anne Cecilie Nygård
Annec Design

www.annec.no<http://www.annec.no/>
tlf: 932 88 706
[cid:image001.png@01D642ED.7CE01170]

Fra: Marcus <notifications@github.com>
Sendt: fredag 12. juni 2020 14.54
Til: vippsas/vipps-recurring-woocommerce <vipps-recurring-woocommerce@noreply.github.com>
Kopi: knotteliten85 <post@annec.no>; Author <author@noreply.github.com>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Not compatible with Wordpress 5.4.2 (#17)


Hei igjen,

Vi tar dette på norsk siden det sikkert er lettere 😄

Har du en testside det er mulig å gi meg tilgang til? (e-post: marcus.dahl@everyday.no<mailto:marcus.dahl@everyday.no>). Jeg tror det er best at jeg får tatt en ordentlig titt på problemet siden det er så mye forskjellig som kan være feil.

Jeg testet nettopp å ha WooCommerce (versjon 4.2.0), WooCommerce Subscriptions og begge Vipps-pluginene installert samtidig på Wordpress 5.4.2 og jeg opplever ikke det samme problemet, noe som er veldig snodig!

**Comment by Marcuzz** [comment]
Hei igjen,

Jeg har nå tatt en titt (jeg byttet også passord og logget ut andre enheter fra min konto pga at opplysningene som du sender til GitHub ligger offentlig)

Det ser ut som at dere bruker noe som heter selz.com i stedet for WooCommerce på kjøpssiden deres, her kommer bare iZettle opp som en betalingsløsning. Hvis jeg går direkte til et WooCommerce produkt så dukker Vipps opp på vanlig måte. For å bruke Vipps faste betalinger med WooCommerce må selz.com integrasjonen fjernes og WooCommerce må brukes i stedet

**Comment by knotteliten85** [comment]
Hei Marcus
Takk for at du har tatt en titt😊
Izettle er den gamle nettbutikk løsningen og den du kommer til dersom du ser produktene fra forsiden eller en av undersidene på nettsiden.
Den er integrert som en app og styres fra Izettle. Alle izettle produktene er lagt inn i Izettle og ikke i WP.  Har latt den være aktiv inntil ny nettside er ferdig.

Produktene som ligger i Woocommerce er til den nye nettbutikken.  Du kan bare se sidene i browseren ved å gå til Templates > Teme builder og klikker på enten Proudkt mal eller Kategori mal. Da åpner Elementor seg og du kan klikke på øyet nederst for å få opp produkt eller kategori siden.
Glemte jo helt å fortelle deg det.

Jeg har forsøkt å deaktivere Izettle, men det hjelper ikke.  Vipps er fortsatt ikke synlig og man kommer ikke til Vipps handlekurv side når du klikker på Legg i handlekurv knappen.

Problemet gjelder kun produktene som er lagt inn som Woocommers subscriptions.  De andre produktene fungerer fint og man kommer til Vipps handlekurv.

Vennlig hilsen
Anne Cecilie Nygård
Annec Design

www.annec.no<http://www.annec.no/>
tlf: 932 88 706
[cid:image001.png@01D64306.6623B810]

Fra: Marcus <notifications@github.com>
Sendt: mandag 15. juni 2020 10.57
Til: vippsas/vipps-recurring-woocommerce <vipps-recurring-woocommerce@noreply.github.com>
Kopi: knotteliten85 <post@annec.no>; Author <author@noreply.github.com>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Not compatible with Wordpress 5.4.2 (#17)


Hei igjen,

Jeg har nå tatt en titt (jeg byttet også passord og logget ut andre enheter fra min konto pga at opplysningene som du sender til GitHub ligger offentlig)

Det ser ut som at dere bruker noe som heter selz.com i stedet for WooCommerce på kjøpssiden deres, her kommer bare iZettle opp som en betalingsløsning. Hvis jeg går direkte til et WooCommerce produkt så dukker Vipps opp på vanlig måte. For å bruke Vipps faste betalinger med WooCommerce må selz.com integrasjonen fjernes og WooCommerce må brukes i stedet

**Comment by Marcuzz** [comment]
Hei,

Jeg ser Vipps på bunnen som en betalingsløsning her: 
![image](https://user-images.githubusercontent.com/3168421/84641803-e0d06700-aefb-11ea-8780-e43d6cea80fb.png)

Men, det jeg ser er at dere må sette produktene som "virtual", eller sette opp frakt hvis produktene ikke skal være virtuelle.

**Comment by knotteliten85** [comment]
Var nettopp inne og sjekket selv, og det ser ut til å fungere nå, ja 😊
Så rart.  Kanskje det hadde noe med minnet i min browser å gjøre?
Men, skulle ikke Vipps hurtigkasse knappen også være synlig i handlekurven?

Vennlig hilsen
Anne Cecilie Nygård
Annec Design

www.annec.no<http://www.annec.no/>
tlf: 932 88 706
[cid:image001.png@01D64314.D74CCD70]

Fra: Marcus <notifications@github.com>
Sendt: mandag 15. juni 2020 11.33
Til: vippsas/vipps-recurring-woocommerce <vipps-recurring-woocommerce@noreply.github.com>
Kopi: knotteliten85 <post@annec.no>; Author <author@noreply.github.com>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Not compatible with Wordpress 5.4.2 (#17)


Hei,

Jeg ser Vipps på bunnen som en betalingsløsning her:
[image]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3168421%2F84641803-e0d06700-aefb-11ea-8780-e43d6cea80fb.png&data=02%7C01%7C%7C9afd6d6ce0b24e59976f08d8110f2b9e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637278104130891168&sdata=EUZs1wgdskyOHADf1N%2FqQNXYUQNJjdTtyhuPwaUsa2k%3D&reserved=0>

Men, det jeg ser er at dere må sette produktene som "virtual", eller sette opp frakt hvis produktene ikke skal være virtuelle.

**Comment by Marcuzz** [comment]
Vipps hurtigkasse er ikke en del av faste betalinger, kun enkeltbetalinger 😄

**Comment by knotteliten85** [comment]
Ok, da er alt i orden 😊
Tusen takk for god hjelp Marcus 😊

Vennlig hilsen
Anne Cecilie Nygård
Annec Design

www.annec.no<http://www.annec.no/>
tlf: 932 88 706
[cid:image001.png@01D64320.D28BCC80]

Fra: Marcus <notifications@github.com>
Sendt: mandag 15. juni 2020 14.14
Til: vippsas/vipps-recurring-woocommerce <vipps-recurring-woocommerce@noreply.github.com>
Kopi: knotteliten85 <post@annec.no>; Author <author@noreply.github.com>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Not compatible with Wordpress 5.4.2 (#17)


Vipps hurtigkasse er ikke en del av faste betalinger, kun enkeltbetalinger 😄

**Comment by Marcuzz** [comment]
Så flott! Bare hyggelig 😃
