### ISSUE TITLE
Direct capture

### ISSUE THREAD

**Issue by RashidJa** [vippsas/vipps-recurring-woocommerce#2]
Should there not be an option to capture charge instantly, f. ex. for subscriptions that include both virtual access and physical product?

**Comment by Marcuzz** [comment]
This will definitely be implemented 👍

**Comment by Marcuzz** [comment]
This will be in version 1.1.0 of the plugin :)

For anyone reading this issue in the future: The above use case is a valid use case for this feature, but if you sell tangible goods (physical goods) you should not charge the customer before you've shipped the product.
