### ISSUE TITLE
Truncate product fields

### ISSUE THREAD

**Issue by o1ie** [vippsas/vipps-recurring-woocommerce#21]
Failing to initialise payment.
Could this be increased? Or truncated by the plugin?
Product name and description (and others that might have issues?)

```
2020-09-07T14:55:10+00:00 DEBUG 
==== Vipps Recurring Version: 1.4.1 ====
==== Start Log ====
[21439] Error in process_payment: initialCharge.description: size must be between 0 and 45
productName: size must be between 0 and 45

```

**Comment by Marcuzz** [comment]
Thanks 😄 

Fixed in 78222f2aa33232649c0aeddfd9fda40a5b875fb6 and 56424d59eb659e56f06b2f63c0cc01e5b535a520
