### ISSUE TITLE
Conflict with Klarna checkout

### ISSUE THREAD

**Issue by Marcuzz** [vippsas/vipps-recurring-woocommerce#34]
https://wordpress.org/support/topic/vipps-recurring-not-working-with-klarna-checkout/

**Comment by Marcuzz** [comment]
A little update on this: It looks like I have to wait for Klarna to review my account before they'll even let me access test keys.

**Comment by Marcuzz** [comment]
This seems to happen with the following conditions only:

* Klarna Checkout and Vipps for WooCommerce Subscriptions are both enabled.
* “Enable automatic retry of failed recurring payments” is enabled in WooCommerce.
* You’re buying a product that has a synchronised renewal.

A scheduled action for renewal (woocommerce_scheduled_subscription_payment) is not created when all these conditions are met. I have yet to figure out why.

**Comment by o1ie** [comment]
Hi @Marcuzz 
Are you any closer to a solution to this or a workaround (keeping both vipps and klarna for recurring)?

**Comment by Marcuzz** [comment]
Hi,

I'm unable to re-create the issue with the latest version of the plugin (the unreleased GitHub version), it would be much appreciated if someone could tell me exactly how to re-create the issue on a somewhat barebones installation of WooCommerce 😅

It seems like I'm able to make payments via Vipps Recurring Payments just fine even when Klarna is enabled. I can even trigger a renewal without any issues.

**Comment by Marcuzz** [comment]
Closing because I can't reproduce this issue.
