### ISSUE TITLE
WooCommerce Subscriptions API v1

### ISSUE THREAD

**Issue by MariusLunde** [vippsas/vipps-recurring-woocommerce#39]
Hi, Im not able to parse payment_details->post_meta->_agreement_id via WooCommerce Subscriptions API v1.

The reason is most likely that there are no filter for 'woocommerce_subscription_payment_meta' in order to register payment_details->post_meta.

link for docs: [here](https://github.com/woocommerce/woocommerce-subscriptions-importer-exporter#importing-payment-gateway-meta-data)

**Comment by Marcuzz** [comment]
Hey, can you download the latest zip from GitHub and see if that version fixes your issue?
