### ISSUE TITLE
Abort in Vipps returns incorrectly

### ISSUE THREAD

**Issue by dinamo-morten** [vippsas/vipps-recurring-woocommerce#43]
Hi,

We have an installation for a client using Vipps & Vipps recurring (https://kingsvenner.dev.webcore.no). If a user klicks on cancel in Vipps (https://api.vipps.no/vippsgateway?v=2&token=.....) - before entering phone-number - control is returned to "Thank you for your order" page and an order is created. In settings for vipps recurring we have set "Cancelled order redirect page" to the page responsible for handling this. (https://kingsvenner.dev.webcore.no/avlyst-vippsbetaling/).

Are we doing something obviously wrong or is this a known issue?

WP 5.7.2
Woo: 5.4.1
Woo subscriptions: 3.0.4
Vipps recurring: 1.8.0

**Comment by Marcuzz** [comment]
Hi Morten,

Are you able to download the latest version from GitHub (https://github.com/vippsas/vipps-recurring-woocommerce/archive/refs/heads/master.zip) and test it on that version?

It looks like we forgot to stop the rest of the code from executing after attempting to redirect to the page, and that made it not redirect to the correct page every time.

**Comment by dinamo-morten** [comment]
Hi,

Downloaded and installed latest version, 1.8.1.
Unfortunately, user is still returned to "Thank you" page if clicking "cancel", link looks like this:

https://kingsvenner.dev.webcore.no/kassen/order-received/1317/?key=wc_order_w8c6iNg5ugeFf

This is also the link assigned to "go back" button if there is a timeout.

Solution can be tested here:

https://kingsvenner.dev.webcore.no/bli-venn/


Morten Rønseth
Tech lead / senior utvikler

M (+47) 99 16 80 00

Dinamo
Storgata 2
0155 Oslo

www.dinamo.no<https://www.dinamo.no/>

________________________________
Fra: Marcus ***@***.***>
Sendt: fredag 18. juni 2021 15:23
Til: vippsas/vipps-recurring-woocommerce ***@***.***>
Kopi: Morten Rønseth ***@***.***>; Author ***@***.***>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Abort in Vipps returns incorrectly (#43)


Hi Morten,

Are you able to download the latest version from GitHub (https://github.com/vippsas/vipps-recurring-woocommerce/archive/refs/heads/master.zip<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvippsas%2Fvipps-recurring-woocommerce%2Farchive%2Frefs%2Fheads%2Fmaster.zip&data=04%7C01%7Cmorten%40dinamo.no%7C80401ff489fa42b3d9dc08d9325c3951%7Cd082a1fa3f014efc8d216a61c1670a24%7C0%7C0%7C637596195296780320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CSpJLepuzx5THUrt3unaaJVMXlDvnnyD8af%2FI7i6j1g%3D&reserved=0>) and test it on that version?

It looks like we forgot to stop the rest of the code from executing after attempting to redirect to the page, and that made it not redirect to the correct page every time.

**Comment by Marcuzz** [comment]
The cancel link is supposed to go to "order received" as the Recurring API does not have a dedicated cancel URL like the e-com single payments API, but you are supposed to be redirected to the "Cancelled order redirect page" set in your settings. I am not able to reproduce this behaviour locally or on any of the merchants running 1.8.1 and that's why I need to ask some additional questions:

- What status are pending payments set to in WooCommerce for you? The redirect only happens when the order status is **NOT**: completed (fullført) or processing (behandler)

**Comment by dinamo-morten** [comment]
Hei,

In vipps recurring:

Default status to give orders with a reserved charge - on hold

Default status to give pending renewal orders - on hold

Any other places to set this?

Morten Rønseth
Tech lead / senior utvikler

M (+47) 99 16 80 00

Dinamo
Storgata 2
0155 Oslo

www.dinamo.no<https://www.dinamo.no/>

________________________________
Fra: Marcus ***@***.***>
Sendt: mandag 21. juni 2021 10:33
Til: vippsas/vipps-recurring-woocommerce ***@***.***>
Kopi: Morten Rønseth ***@***.***>; Author ***@***.***>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Abort in Vipps returns incorrectly (#43)


The cancel link is supposed to go to "order received" as the Recurring API does not have a dedicated cancel URL like the e-com single payments API, but you are supposed to be redirected to the "Cancelled order redirect page" set in your settings. I am not able to reproduce this behaviour locally or on any of the merchants running 1.8.1 and that's why I need to ask some additional questions:

  *   What status are pending payments set to in WooCommerce for you? The redirect only happens when the order status is NOT: completed (fullført) or processing (behandler)

**Comment by Marcuzz** [comment]
The only other place would be if another plugin does this.. hmm.

Can you try downloading the latest version from GitHub again? I've added a debug log message that should be able to tell us more. Make sure to enable the "Log debug messages" option in the Vipps Recurring Payments settings.

Now try checking out again and hit "Cancel". If you search for `process_redirect_payment` in the latest `woocommerce-gateway-vipps-recurring` log found in WooCommerce -> Status -> Logs. What does it say?

**Comment by dinamo-morten** [comment]
Hei,

Are you sure github is updated? Log-message doesn't look any different from before:

2021-06-21T09:07:03+00:00 DEBUG
==== Vipps Recurring Version: 1.8.1 ====
==== Start Log ====
[1332] process_payment (gateway change: No)
Created agreement with agreement ID: agr_2VRJvbP
Debug body: {"currency":"NOK","price":15000,"interval":"MONTH","intervalCount":1,"productName":"St\u00f8tt oss fast","productDescription":"St\u00f8tt oss fast","isApp":false,"merchantAgreementUrl":"https:\/\/kingsvenner.dev.webcore.no\/min-konto\/","merchantRedirectUrl":"https:\/\/kingsvenner.dev.webcore.no\/kassen\/order-received\/1332\/?key=wc_order_9pF0i83h7OlDb","initialCharge":{"amount":15000,"currency":"NOK","description":"St\u00f8tt oss fast","transactionType":"DIRECT_CAPTURE"}}
Debug response: {"vippsConfirmationUrl":"redacted","agreementResource":"https:\/\/api.vipps.no\/recurring\/v2\/agreements\/agr_2VRJvbP","agreementId":"agr_2VRJvbP","chargeId":"chr-79VzUFd"}
==== End Log ====

Could I maybe give you admin-login to wp-admin?


Morten Rønseth
Tech lead / senior utvikler

M (+47) 99 16 80 00

Dinamo
Storgata 2
0155 Oslo

www.dinamo.no<https://www.dinamo.no/>

________________________________
Fra: Marcus ***@***.***>
Sendt: mandag 21. juni 2021 10:57
Til: vippsas/vipps-recurring-woocommerce ***@***.***>
Kopi: Morten Rønseth ***@***.***>; Author ***@***.***>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Abort in Vipps returns incorrectly (#43)


The only other place would be if another plugin does this.. hmm.

Can you try downloading the latest version from GitHub again? I've added a debug log message that should be able to tell us more. Make sure to enable the "Log debug messages" option in the Vipps Recurring Payments settings.

Now try checking out again and hit "Cancel". If you search for process_redirect_payment in the latest woocommerce-gateway-vipps-recurring log found in WooCommerce -> Status -> Logs. What does it say?

**Comment by Marcuzz** [comment]
Yeah that might be easier. My email address is marcus.dahl@everyday.no

GitHub is updated, but this could mean it's failing earlier in the chain but I could debug that with access :)

**Comment by dinamo-morten** [comment]
Hi,

User: marcus
Password: ZRJmjywkkcUH56Tv
URL: https://kingsvenner.dev.webcore.no/wp-admin


Morten Rønseth
Tech lead / senior utvikler

M (+47) 99 16 80 00

Dinamo
Storgata 2
0155 Oslo

www.dinamo.no<https://www.dinamo.no/>

________________________________
Fra: Marcus ***@***.***>
Sendt: mandag 21. juni 2021 11:10
Til: vippsas/vipps-recurring-woocommerce ***@***.***>
Kopi: Morten Rønseth ***@***.***>; Author ***@***.***>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Abort in Vipps returns incorrectly (#43)


Yeah that might be easier. My email address is ***@***.******@***.***>

GitHub is updated, but this could mean it's failing earlier in the chain but I could debug that with access :)

**Comment by Marcuzz** [comment]
Thanks! I logged in and changed the password immediately and deleted your comment from here, GitHub issues is a public area and we don't want someone else logging in 😅

**Comment by dinamo-morten** [comment]
😄 didn't see that comming, responding via email...


Morten Rønseth
Tech lead / senior utvikler

M (+47) 99 16 80 00

Dinamo
Storgata 2
0155 Oslo

www.dinamo.no<https://www.dinamo.no/>

________________________________
Fra: Marcus ***@***.***>
Sendt: mandag 21. juni 2021 11:16
Til: vippsas/vipps-recurring-woocommerce ***@***.***>
Kopi: Morten Rønseth ***@***.***>; Author ***@***.***>
Emne: Re: [vippsas/vipps-recurring-woocommerce] Abort in Vipps returns incorrectly (#43)


Thanks! I logged in and changed the password immediately and deleted your comment from here, GitHub issues is a public area and we don't want someone else logging in 😅

**Comment by Marcuzz** [comment]
Yeah, GitHub automatically posts the replies to the issues section :D 

Anyway, is it possible to give me access to manage plugins so that I can upload new test versions of the Vipps Recurring Payments plugin?

**Comment by Marcuzz** [comment]
**Here's a summary of what caused this issue in this specific case**

The following line of code was missing in their `checkout/thankyou.php` template

```php
<?php do_action( 'woocommerce_thankyou', $order->get_id() ); ?>
```

If anyone else comes across this issue please check that the above code is present in the template file 😃
