### ISSUE TITLE
Support for All Products for Woocommerce Subscriptions

### ISSUE THREAD

**Issue by danielcherubini** [vippsas/vipps-recurring-woocommerce#58]
https://woocommerce.com/document/all-products-for-woocommerce-subscriptions/

Hi

It would seem that this payment option doesn't work for one of the official woocommerce subscription plugins. This plugin enables products to be added to subscription plans easier than doing variable subscriptions. Attached is an example of one of our products.

![image](https://user-images.githubusercontent.com/399473/162620776-abcea9e4-086c-47a3-a87e-9b130c21d764.png)

When taking this product through to the checkout, it would seem that this payment option ignores it, probably because it is a "simple-product" and not a "subscription" type product, either simple or variable... 

We need to use this method for ease of use, and easy price calculations.. since we have a bot that changes the prices on the website..

Here's how it looks during the checkout

![image](https://user-images.githubusercontent.com/399473/162620862-a80f2cda-a901-4291-9390-ddf06c26a140.png)

If there's anymore info you need please let me know.

**Comment by danielcherubini** [comment]
So you know what the structure of a product looks like i've attached one of the exports 
[wc-product-export-8-4-2022-1649414420014.csv](https://github.com/vippsas/vipps-recurring-woocommerce/files/8462590/wc-product-export-8-4-2022-1649414420014.csv)

you can see there is a metadata field `Meta: _wcsatt_schemes` that contains data if it is a WooCommerce All product Subscription scheme.

I think I have found the code on line 411 of woo-vipps-recurring.php

**Comment by danielcherubini** [comment]
There's a kind of issue with the fix for `wc-gateway-vipps-recurring.php`

Essentially, you're using `WC_Subscriptions_Product::is_subscription()` to check if it is a subscription type product, which that SHOULD return a true, since this type of product IS a subscription product.. .but it seems that Woo hasn't added a check in that function for if its a Wcsatt type of subscription...

So the two changes should be to add a check to see IF its a simple type product that has the `_wcsatt` metadata.

**Comment by Marcuzz** [comment]
Hi Daniel,

I had never even heard of this plugin before, but it does seem like it isn't integrating with WooCommerce Subscriptions in the way one would expect, causing us to need additional logic to support it.

I will look into this after the Easter break, as I currently have holiday.

If you are able to fix it in the meantime feel free to submit a pull request and I'll verify that everything works once I'm back 🙂

**Comment by danielcherubini** [comment]
I was able to temporarily bypass it. Those two lines I just changed it so
that single products were ok which isn't optimal, there would need to be an
additional check. And on the other line I just changed it to return true
every time. Which again isn't optimal. But since all our products are
exactly the same it's fine for now.

Will this have any knock on effects with cancelling or refunding?

**Comment by danielcherubini** [comment]
OK that's good to know, i had a quick poke around in the source of the plugin.. and it seems like it has functions that are overrides to the standard ones.. 

that said, go enjoy Påskeferie...

**Comment by Marcuzz** [comment]
Added in 1.14.0 (not released yet, will have to do some more testing first).
