### ISSUE TITLE
Uncaught TypeError triggers fatal error in PHP 8.0

### ISSUE THREAD

**Issue by magnuskl** [vippsas/vipps-recurring-woocommerce#62]
[Line 1104](https://github.com/vippsas/vipps-recurring-woocommerce/blob/6190bc09d05fad07f7c3dca7e3bfe09a04738184/includes/wc-gateway-vipps-recurring.php#L1104) in [wc-gateway-vipps-recurring.php](https://github.com/vippsas/vipps-recurring-woocommerce/blob/master/includes/wc-gateway-vipps-recurring.php) tends to produce an uncaught `TypeError` when `$agreement_id` is a string. This triggers a mere warning in PHP 7.4—but a fatal error in PHP 8.0, causing the script to abort. See also: [PHP Manual](https://www.php.net/manual/en/index.php) → [Appendices](https://www.php.net/manual/en/appendices.php) → [Migrating from PHP 7.4.x to PHP 8.0.x](https://www.php.net/manual/en/migration80.php) → [Backward Incompatible Changes](https://www.php.net/manual/en/migration80.incompatible.php).

**Comment by Marcuzz** [comment]
Hi,

Thanks for reporting this bug. I think we are using the wrong variable here. I'll look into it.

**Comment by magnuskl** [comment]
Other instances of this bug seem to be present elsewhere in the code, producing the same error. For instance see, see [line 1030](https://github.com/vippsas/vipps-recurring-woocommerce/blob/6190bc09d05fad07f7c3dca7e3bfe09a04738184/includes/wc-gateway-vipps-recurring.php#L1030), also in [wc-gateway-vipps-recurring.php](https://github.com/vippsas/vipps-recurring-woocommerce/blob/master/includes/wc-gateway-vipps-recurring.php).

**Comment by Marcuzz** [comment]
This should be fixed when [feat/api-v3](https://github.com/vippsas/vipps-recurring-woocommerce/tree/feat/api-v3) is merged, as everything has been refactored to use classes in and out of the API now. I will finish that branch up shortly – it should already be fully working, although it is missing some error handling code and I don't want to make any guarantees yet.

For now I'll re-open this issue in-case it is still an issue somewhere within api-v3, which I will check soon. There may be places where we're grabbing data from WooCommerce where a class for the given resource is not yet instantiated

**Comment by magnuskl** [comment]
I do not see that error occurring in the PHP error logs anymore.
