### ISSUE TITLE
Vipps Checkout - not showing recurring amount

### ISSUE THREAD

**Issue by Kontordama** [vippsas/vipps-recurring-woocommerce#63]
When proceeding to checkout for a simple subscription service (donations), the Vipps Checkout page is for a single product (one time fee) and the recurring amount is not registered.

**Comment by Marcuzz** [comment]
Hi,

If you are using Vipps Checkout as the default "checkout" page, it does not support recurring subscriptions. Make sure the standard checkout page is chosen as the default checkout page instead of Vipps Checkout. Otherwise recurring payments do not work.

**Comment by Kontordama** [comment]
Thank you, Marcuzz.
