### ISSUE TITLE
Scheduled actions

### ISSUE THREAD

**Issue by esbnews** [vippsas/vipps-recurring-woocommerce#65]
Hi

My system generates an error connected to Vipps fast trekk and Woocommerce Subscriptions when a recurring action runs:

"scheduled action 188853 (subscription payment) failed to finish processing due to the following error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /customers/3/d/8/xxxxx.no/httpd.www/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/templates/emails/customer-processing-renewal-order.php:19"

I wonder how to work this out, and am not sure if it's a Vipps problem or Woocommerce Subscriptions problem. I got the full errorlog if anyone can look at this.

Best regards, Esben Holm Eskelund

**Comment by Marcuzz** [comment]
Hi,

Can you enable debugging/error messages in the Vipps Recurring Payments settings? When it happens again you should be able to see a more detailed error in the Vipps Recurring Payments logs in WooCommerce -> Status -> Logs. That should be able to tell us more about what issue you are experiencing here.

In general the sending of emails (which this error looks to be related to) is not something Vipps Recurring Payments deals with, that's something WooCommerce Subscription deals with on it's own, so I'm not so sure this is a problem with this plugin at the moment.

**Comment by esbnews** [comment]
I think you're right, and this migth have a connection to faulty translation code in Woocommerce Subscriptions, in fact.

**Comment by Marcuzz** [comment]
That's very strange, although it can of course happen 😅

Please keep us updated if it turns out to be related to the plugin :)
