### ISSUE TITLE
Limited subscriptions show up as unlimited in Vipps app

### ISSUE THREAD

**Issue by RashidJa** [vippsas/vipps-recurring-woocommerce#66]
On time limited subscriptions it says in the Vipps app that the subscription lasts «til du sier opp». Would it be possible to show the end date instead?

**Comment by Marcuzz** [comment]
Hey,

I asked the beautiful people at Vipps about this and it looks like there are no plans to allow changing this text as of now, but it is something they will look into. 

They weren't aware of a use case where subscriptions have an end date, would you mind sharing some details about your use case? If you prefer to do it in private you can email me at marcus.dahl@everyday.no 🙂

**Comment by Marcuzz** [comment]
Oh okay, so the usage is to inform/reassure the gift giver that the subscription has an end date.

May I ask why you chose to use a subscription for gift subscriptions instead of a simple product?
