### ISSUE TITLE
Subscription status: Pending med Vipps faste betalinger

### ISSUE THREAD

**Issue by ElenaTekniskM** [vippsas/vipps-recurring-woocommerce#68]
Hei,
Vi har Woocommerce, Membership, Vipps osv på corefit.no nettstdet og har problemer med Vipps faste betaling.  Noen av kundene som velger Vipps faste betalinger, betaler kun en gang, mens de andre betalingene ikke blir trukket.  Subscription status viser "Pending", og betalingen går ikke via Vipps, men kunden forblir fortsatt active og for tilgang til trening senter. 
Kan dere gi meg noen tips om hvordan jeg kan fikse dette problemet? Det ville være flott hvis noen kunne hjelpe meg via fjernstyring. Tusen takk på forhånd!
If I'm in the wrong place, just send me to rhit one and delete the issue

**Comment by Marcuzz** [comment]
I'm going to close this issue as it was answered via the WP support forum & email.

If you are still experiencing issues, please don't hesitate to contact us again :)
