### ISSUE TITLE
Please update the links to point to the new vipps website

### ISSUE THREAD

**Issue by rebekaburnett** [vippsas/vipps-recurring-woocommerce#71]
See: https://github.com/vippsas/vipps-recurring-woocommerce/pull/70

**Comment by Marcuzz** [comment]
There are some more occurrences of `vipps.no`: https://github.com/search?q=repo%3Avippsas%2Fvipps-recurring-woocommerce%20vipps.no&type=code

I assume all of them except the API URLs need to be updated, right? I can't find an equivalent for portal.vipps.no yet, though

**Comment by rebekaburnett** [comment]
I think those are ok for now, as long as they still work. The vippsmobilepay.com site is still pretty empty and they are referring people to vipps.no.

**Comment by Marcuzz** [comment]
Okay, thank you 😄
