### ISSUE TITLE
Refund throwing error

### ISSUE THREAD

**Issue by RashidJa** [vippsas/vipps-recurring-woocommerce#77]
I'm getting the following error when trying to refund an order:  PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order_Refund::get_payment_method() in /wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-vipps-recurring-helper.php:221

Stack trace:
#0 /plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-gateway-vipps-recurring.php(2042): WC_Vipps_Recurring_Helper::get_payment_method()
#1 /class-wp-hook.php(310): WC_Gateway_Vipps_Recurring->update_agreement_price_in_app()
#2 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#3 /wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1941): do_action()
#5 /wp-content/plugins/woocommerce/includes/wc-order-functions.php(606): WC_Abstract_Order->calculate_totals()
#6 /wp-content/plugins/woocommerce/includes/class-wc-ajax.php(2199): wc_create_refund()
#7 /wp-includes/class-wp-hook.php(310): WC_AJAX::refund_line_items()
#8 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#9 /wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /wp-admin/admin-ajax.php(188): do_action()
#11 {main}
  thrown in /wp-content/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-vipps-recurring-helper.php on line 221

**Comment by Marcuzz** [comment]
Thank you for reporting this error, we have now fixed it in version 1.16.5 of the plugin 🎉
