### ISSUE TITLE
Critical: Cancelling payment in Vipps creates order and sends you to thank you page

### ISSUE THREAD

**Issue by kimmenbert** [vippsas/vipps-recurring-woocommerce#92]
If you proceed to Vipps payment and press cancel either in the popup-window or in the app, the payment gets "processed" and you're greeted with "Thank you for your order" on the order-recieved page.

An cancelled order is created and a cancelled Woo Subscription gets created.

Expected action should be to return to checkout page, with a WooCommerce notice, so the customer can try again or change their payment method

**Comment by Marcuzz** [comment]
Hi,

Do other payment gateways in WooCommerce do what you're describing?

The behaviour of Vipps/MobilePay recurring payments should be identical to other payment gateways from a WooCommerce point of view :)

If that's not the case then please tell us which gateway(s) work differently 😄

**Comment by kimmenbert** [comment]
Ignore the canceled order created, many payment gateways do create the cancelled orders. The critical part here is that you get sent to thank you page, indicating you completed your order.

Most payment methods return to checkout with a WooCommerce notice, keeping the initial generated order in awaiting payment and allow you to retry payment.

The regular Vipps plugin redirects you to a custom page with «continue shopping»

I think that as long as you add a new wc notice, the checkout process should stop and allow you to retry same / another payment gateway

**Comment by kimmenbert** [comment]
Messed up and closed the issue. Reopening with this

**Comment by Marcuzz** [comment]
Thank you for the clarification. That makes more sense. I will look into this 😄

**Comment by kimmenbert** [comment]
Hi, Any updates here?

**Comment by Marcuzz** [comment]
Hi,

I'm looking into this right now, but might have to continue debugging tomorrow.

**Comment by Marcuzz** [comment]
Do you think a screen like this will suffice? Appearing directly after the payment redirect.

![image](https://github.com/vippsas/vipps-recurring-woocommerce/assets/3168421/367c2504-a4ef-444c-b42c-1eebf8eb2687)

The difference between Vipps MobilePay recurring payments and other gateways is that we actually have no "cancellation url" redirect, thus we need to have a catch-all page. 

I could redirect to a page that mimics a page in your own theme/setup from the redirect page, but I'm not sure if that's preferred(?).
