### ISSUE TITLE
Fatal error when changing order status to "Failed"

### ISSUE THREAD

**Issue by kimmenbert** [vippsas/vipps-recurring-woocommerce#94]
Tested on an order originally paid for with Vipps express (non subscription).

Changing order status to "Failed" produces fatal error:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_meta() on null in /xxxx/plugins/vipps-recurring-payments-gateway-for-woocommerce/includes/wc-vipps-recurring-helper.php:188
```

Also seems to happen on other status changes. Randomly or maybe a pattern like Failed -> Canceled

**Comment by Marcuzz** [comment]
This should be fixed in 869646b. You can download the update from GitHub. I will release the update on WordPress.org when we've dealt with the other issues as well 😄
